// export { applyPointChanges } from './utils/changes';
export * from './components'
export { default as ReactFabric } from './container/ReactFabric'
export { useReactFabric } from './hooks/useReactFabric'
export { useZoom } from './hooks/useZoom'
export * from './utils'
export { PluginGrid, PluginFreeRect } from './plugins'
export type { PluginFreeRectProps } from './plugins'
export { default as PluginToolbarVertical } from './toolbar/Vertical'
export type { ToolbarVerticalProps } from './toolbar/Vertical'
